baseURL: "http://ilmfruits.com/"
title: "Ilm Fruits"
footnoteReturnLinkContents: "↩"
permalinks:
  post: /:year/:title/
params:
  Subtitle: "The Sweetness of Faith Lies in the Fruits of Knowledge"
  AuthorName: "Ilm Seeker"
  SidebarRecentLimit: 99
theme: "beg"